builder:
  track: dev

labels:
  app-group: estafette-ci
  team: estafette-team
  language: helm

version:
  semver:
    major: 1
    minor: 0
    patch: 1
    labelTemplate: '{{branch}}-{{auto}}'
    releaseBranch: 1.0.1

stages:
  lint-and-package:
    parallelStages:
      lint-helm-chart:
        image: extensions/helm:dev
        action: lint

      package-helm-chart:
        image: extensions/helm:dev
        action: package

  test-helm-chart:
    services:
    - name: kubernetes
      image: bsycorp/kind:latest-1.19
      readiness:
        path: /kubernetes-ready
        port: 10080
        timeoutSeconds: 120
    image: extensions/helm:dev
    action: test
    values: |-
      db:
        conf:
          single-node: true
        statefulset:
          replicas: 1
        storage:
          persistentVolume:
            enabled: false
            size: 1Gi
        tls:
          enabled: false

      api:
        deployment:
          extraVolumes: |
          extraVolumeMounts: |

      db-migrator:
        job:
          env:
          - name: COCKROACH_CONNECTION_STRING
            value: postgresql://root@estafette-ci-db-public:26257/defaultdb?sslmode=disable
          extraVolumes: |
          extraVolumeMounts: |

  clone-charts-repo:
    image: extensions/git-clone:dev
    repo: helm-charts
    branch: main

  publish-helm-chart:
    image: extensions/helm:dev
    action: publish
    repoBranch: main

  slack-notify:
    image: extensions/slack-build-status:dev
    workspace: estafette
    channels:
    - '#build-status'
    when:
      status == 'succeeded' ||
      status == 'failed'

releases:
  release:
    stages:
      clone-charts-repo:
        image: extensions/git-clone:dev
        repo: helm-charts
        branch: main

      purge-prerelease-helm-charts:
        image: extensions/helm:dev
        action: purge
        repoBranch: main

      create-github-release:
        image: extensions/github-release:dev

  helm-diff:
    stages:
      diff:
        image: extensions/helm:dev
        credentials: gke-tooling
        action: diff
        tillerless: true
        namespace: estafette-ci

  tooling-estafette:
    actions:
    - name: diff
    - name: install
    stages:
      deploy:
        image: extensions/helm:dev
        namespace: estafette-ci
        release: estafette-ci
        timeout: 300s
        values: |-
          db:
            enabled: false

          api:
            enabled: false

          web:
            enabled: false

          db-migrator:
            enabled: false

          cron-event-sender:
            enabled: false

          metrics:
            enabled: true
            server:
              replicaCount: 2
              statefulSet:
                enabled: true
              persistentVolume:
                enabled: true

            serverFiles:
              prometheus.yml:
                scrape_configs:
                  - job_name: 'kubernetes-nodes-resource'
                    scheme: https
                    tls_config:
                      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                      insecure_skip_verify: true
                    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
                    kubernetes_sd_configs:
                      - role: node
                    relabel_configs:
                      - action: labelmap
                        regex: __meta_kubernetes_node_label_(.+)
                      - target_label: __address__
                        replacement: kubernetes.default.svc:443
                      - source_labels: [__meta_kubernetes_node_name]
                        regex: (.+)
                        target_label: __metrics_path__
                        replacement: /api/v1/nodes/$1/proxy/metrics/cadvisor
                    metric_relabel_configs:
                      # keep only the metrics required to calculate max cpu/memory usage by a build/release job
                      - source_labels: [__name__]
                        action: keep
                        regex: container_cpu_usage_seconds_total|container_memory_working_set_bytes
                      # keep only for namespace running build/release jobs
                      - source_labels: [namespace]
                        action: keep
                        regex: .+-jobs

          queue:
            enabled: true

            cluster:
              enabled: true
              replicas: 3

            affinity:
              podAntiAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                - topologyKey: kubernetes.io/hostname
                  labelSelector:
                    matchLabels:
                      app.kubernetes.io/name: queue
                      app.kubernetes.io/instance: estafette-ci

  release:
    stages:
      clone-charts-repo:
        image: extensions/git-clone:dev
        repo: helm-charts
        branch: main

      purge-prerelease-helm-charts:
        image: extensions/helm:dev
        action: purge
        repoBranch: main

      create-github-release:
        image: extensions/github-release:dev