{{- if .Values.config.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "estafette-ci-api.fullname" . }}
  labels:
    {{- include "estafette-ci-api.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.config.files }}
  {{ $k }}: |
    {{- tpl $v $ | nindent 4 }}
  {{- end }}
{{- end -}}
