{{- if $.Values.ingress.enabled -}}
{{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" -}}
apiVersion: networking.k8s.io/v1
{{- else if $.Capabilities.APIVersions.Has "networking.k8s.io/v1beta1/Ingress" -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "estafette-ci-api.fullname" . }}
  labels:
    {{- include "estafette-ci-api.labels" . | nindent 4 }}
  {{- if or $.Values.ingress.annotations $.Values.iap.enabled }}
  annotations:
  {{- with $.Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if $.Values.iap.enabled }}
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.allow-http: "false"
  {{- end }}
  {{- end }}
spec:
  {{- if $.Values.ingress.tls }}
  tls:
    {{- range $.Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ tpl . $ | quote }}
        {{- end }}
      secretName: {{ tpl .secretName $ | quote }}
    {{- end }}
  {{- end }}
  rules:
    {{- range $.Values.ingress.hosts }}
    - host: {{ tpl .host $ | quote }}
      http:
        paths:
          {{- range .paths }}
          {{- if $.Values.iap.enabled }}
          - path: '{{ .path }}*'
          {{- else }}
          - path: {{ .path }}
          {{- end }}
            {{- if .pathType }}
            {{- if $.Values.iap.enabled }}
            pathType: ImplementationSpecific
            {{- else }}
            pathType: {{ .pathType }}
            {{- end }}
            {{- end }}
            backend:
              {{- toYaml .backend | nindent 14 }}
          {{- end }}
    {{- end }}
  {{- end }}
