{{- if and .Values.tls.enabled (not .Values.tls.certManager.enabled) }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "estafette-ci-api.fullname" . }}.tls
  labels:
    {{- include "estafette-ci-api.labels" . | nindent 4 }}
  {{- if or .Values.tls.annotations .Values.tls.keep }}
  annotations:
  {{- with .Values.tls.annotations }}
    {{- range $key, $value := . }}
    {{ $key }}: {{ tpl $value $ | quote }}
    {{- end }}
  {{- end }}
  {{- if .Values.tls.keep }}
    "helm.sh/resource-policy": keep
  {{- end }}
  {{- end }}
{{- if and .Values.tls.cert .Values.tls.key }}
type: kubernetes.io/tls
{{- end }}
data:
  {{- with .Values.tls.cert }}
  tls.crt: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.tls.key }}
  tls.key: {{ . | b64enc }}
  {{- end }}
{{- end }}