{{- if and .Values.tls.enabled (not .Values.tls.certManager.enabled) }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "estafette-ci-api.fullname" . }}.tls
  labels:
    {{- include "estafette-ci-api.labels" . | nindent 4 }}
  {{- with .Values.tls.annotations }}
  annotations:
    {{- toYaml . | nindent 4 -}}
  {{- end }}
{{- if and .Values.tls.cert .Values.tls.key }}
type: kubernetes.io/tls
{{- end }}
data:
  {{- with .Values.tls.cert }}
  tls.crt: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.tls.key }}
  tls.key: {{ . | b64enc }}
  {{- end }}
{{- end }}