apiVersion: v2
appVersion: "1.0"
description: The resilient and cloud-native CI/CD platform
name: estafette-ci
version: 0.1.0
dependencies:
- name: estafette-ci-api
  version: 1.0.5
  repository: https://helm.estafette.io/
  alias: api
  condition: api.enabled
- name: estafette-ci-web
  version: 1.0.5
  repository: https://helm.estafette.io/
  alias: web
  condition: web.enabled
- name: estafette-ci-db-migrator
  version: 1.0.4
  repository: https://helm.estafette.io/
  alias: db-migrator
  condition: db-migrator.enabled
- name: estafette-ci-cron-event-sender
  version: 1.0.4
  repository: https://helm.estafette.io/
  alias: cron-event-sender
  condition: cron-event-sender.enabled

- name: cockroachdb
  version: 6.1.0
  repository: https://charts.cockroachdb.com/
  alias: db
  condition: db.enabled
- name: prometheus
  version: 14.6.0
  repository: https://prometheus-community.github.io/helm-charts
  alias: metrics
  condition: metrics.enabled
- name: nats
  version: 0.8.8
  repository: https://nats-io.github.io/k8s/helm/charts/
  alias: queue
  condition: queue.enabled