apiVersion: v2
appVersion: "1.0"
description: The resilient and cloud-native CI/CD platform
name: estafette-ci
version: 0.1.0
dependencies:
- name: cockroachdb
  version: 5.1.1
  repository: https://charts.cockroachdb.com/
  alias: db
- name: estafette-ci-api
  version: 1.0.0-main-1651
  repository: https://helm.estafette.io/
  alias: api
- name: estafette-ci-web
  version: 1.0.0-main-1071
  repository: https://helm.estafette.io/
  alias: web
- name: estafette-ci-db-migrator
  version: 1.0.0-main-184
  repository: https://helm.estafette.io/
  alias: db-migrator
- name: prometheus
  version: 13.7.0
  repository: https://prometheus-community.github.io/helm-charts
  alias: metrics