# https://github.com/cockroachdb/helm-charts/blob/master/cockroachdb/values.yaml
db:
  statefulset:
    env:
    - name: COCKROACH_SKIP_ENABLING_DIAGNOSTIC_REPORTING
      value: "true"
  tls:
    enabled: true
  service:
    public:
      annotations:
        # required when tls is enabled for cluster and gce ingress is used
        service.alpha.kubernetes.io/app-protocols: '{"http":"HTTPS"}'
  ingress:
    annotations:
      # required when tls is enabled for cluster and nginx ingress is used
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
  init:
    annotations:
      helm.sh/hook: post-install,post-upgrade
      # This will delete job after succeeded
      helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation

# https://github.com/estafette/estafette-ci-api/blob/main/helm/estafette-ci-api/values.yaml
api:
  deployment:
    env:
    - name: JAEGER_DISABLED
      value: 'true'
    extraVolumes: |
      - name: client-certificate
        secret:
          secretName: estafette-ci.client.root
          defaultMode: 384
    extraVolumeMounts: |
      - name: client-certificate
        mountPath: /cockroach-certs
  config:
    enabled: true
    files: |
      config.yaml: |
        database:
          databaseName: defaultdb
          user: root

# https://github.com/estafette/estafette-ci-web/blob/main/helm/estafette-ci-web/values.yaml
web: {}

# https://github.com/estafette/estafette-ci-db-migrator/blob/main/helm/estafette-ci-db-migrator/values.yaml
db-migrator:
  job:
    env:
    - name: COCKROACH_DATABASE
      value: defaultdb
    - name: COCKROACH_USER
      value: root
    extraVolumes: |
      - name: client-certificate
        secret:
          secretName: estafette-ci.client.root
          defaultMode: 384
    extraVolumeMounts: |
      - name: client-certificate
        mountPath: /cockroach-certs