db:
  statefulset:
    resources:
      requests:
        cpu: 1000m
        memory: 4Gi
      limits:
        memory: 4Gi
    podAntiAffinity:
      type: hard
  tls:
    enabled: true
  service:
    public:
      annotations:
        service.alpha.kubernetes.io/app-protocols: '{"http":"HTTPS"}'
  init:
    annotations:
      helm.sh/hook: post-install,post-upgrade
      # This will delete job after succeeded
      helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation

api: {}

web: {}

# estafette-ci-cron-event-sender: {}