image:
  repository: estafette/estafette-ci-db-migrator
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  credentials: {}
    # registry: docker.io
    # username: john_doe
    # password: changeme

# the following log formats are available: plaintext, console, json, stackdriver, v3 (see https://github.com/estafette/estafette-foundation for more info)
logFormat: json

# the following levels and upwards will be logged: disabled, trace, debug, info, warn, error, fatal, panic (see https://github.com/estafette/estafette-foundation for more info)
logLevel: debug

job:
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  podAnnotations: {}
    # prometheus.io/scrape: 'true'
    # prometheus.io/path: '/metrics'
    # prometheus.io/port: '5000'
    # prometheus.io/scheme: 'http'

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  nodeSelector: {}

  tolerations: []

  affinity: {}

  # use to set extra environment variables
  extraEnv: []

  # specify extra containers as a string, interpreted with tpl; this allows use of helm values.
  # - name: {{ .Chart.Name }}-sidecar
  # image: registry/git-sync
  extraContainers: |

  # specify extra volumes 
  extraVolumes: |
    - name: client-certificate
      projected:
        sources:
        - secret:
            name: estafette-ci-db-client-secret
            items:
            - key: ca.crt
              path: ca.crt
              mode: 256
            - key: tls.crt
              path: tls.crt
              mode: 256
            - key: tls.key
              path: tls.key
              mode: 256

  # specify extra volume mounts for the main container
  extraVolumeMounts: |
    - name: client-certificate
      mountPath: /cockroach-certs

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

extraLabels: {}
#   team: estafette

extraSecrets: []
# - key: gcp
#   annotations: {}
#   mountPath: /gcp
#   data:
#     service-account-key.json: |
#       {}

extraConfigmaps: []
# - key: templates
#   annotations: {}
#   mountPath: /templates
#   data: |
#     manifest-docker.tmpl: |
#       labels:
#         container: {{.ContainerName}}
#         team: {{.TeamName}}
#         language: docker

#       stages:
#         bake:
#           image: extensions/docker:stable
#           action: build
#           repositories:
#           - estafette

#         push-to-docker-registry:
#           image: extensions/docker:stable
#           action: push
#           repositories:
#           - estafette

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
