apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "estafette-ci-hanging-job-cleaner.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "estafette-ci-hanging-job-cleaner.labels" . | indent 4 }}
spec:
  schedule: '{{ $.Values.cronjob.schedule }}'
  concurrencyPolicy: {{ $.Values.cronjob.concurrencyPolicy }}
  failedJobsHistoryLimit: {{ $.Values.cronjob.failedJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ $.Values.cronjob.successfulJobsHistoryLimit }}
  suspend: {{ $.Values.cronjob.suspend }}
  jobTemplate:
    spec:
      completions: {{ $.Values.cronjob.completions }}
      parallelism: {{ $.Values.cronjob.parallelism }}
      backoffLimit: {{ $.Values.cronjob.backoffLimit }}
      template:
        metadata:
          labels:
            app.kubernetes.io/name: {{ include "estafette-ci-hanging-job-cleaner.name" . }}
            app.kubernetes.io/instance: {{ .Release.Name }}
            {{- if .Chart.AppVersion }}
            app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
            {{- end }}
            {{- range $key, $value := $.Values.extraPodLabels }}
            {{ $key }}: {{ $value }}
            {{- end }}
          annotations:
            checksum/secrets: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        spec:
          {{- if or $.Values.image.credentials $.Values.imagePullSecrets }}
          imagePullSecrets:
          {{- if $.Values.image.credentials }}
            - name: {{ template "estafette-ci-hanging-job-cleaner.fullname" . }}.registry
          {{- end }}
          {{- with $.Values.imagePullSecrets }}
            {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- end }}
          serviceAccountName: {{ template "estafette-ci-hanging-job-cleaner.serviceAccountName" . }}
          restartPolicy: {{ $.Values.cronjob.restartPolicy }}
          securityContext:
            {{- toYaml $.Values.podSecurityContext | nindent 12 }}
          containers:
            - name: {{ .Chart.Name }}
              securityContext:
                {{- toYaml $.Values.securityContext | nindent 16 }}
              image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default .Chart.Version }}"
              imagePullPolicy: {{ $.Values.image.pullPolicy }}
              {{- with $.Values.extraArgs }}
              args:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              env:
                - name: "ESTAFETTE_LOG_FORMAT"
                  value: "{{ $.Values.logFormat }}"
                - name: "ESTAFETTE_LOG_LEVEL"
                  value: "{{ $.Values.logLevel }}"
                - name: "API_BASE_URL"
                  value: "{{ tpl $.Values.config.apiBaseURL $ }}"
                - name: "CLIENT_ID"
                  value: "{{ $.Values.config.clientID }}"
                - name: "CLIENT_SECRET"
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "estafette-ci-hanging-job-cleaner.fullname" . }}
                      key: clientSecret
                - name: "JOB_NAMESPACE"
                  value: "{{ tpl $.Values.config.jobNamespace $ }}"
              {{- with $.Values.extraEnv }}
                {{- toYaml . | nindent 16 }}
              {{- end }}
              resources:
                {{- toYaml $.Values.resources | nindent 16 }}
          terminationGracePeriodSeconds: 300
          {{- with $.Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- with $.Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with $.Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
        {{- end }}