{{- if $.Values.rbac.enable -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "estafette-ci-hanging-job-cleaner.fullname" . }}
  namespace: {{ include "estafette-ci-hanging-job-cleaner.jobNamespace" . }}
  labels:
{{ include "estafette-ci-hanging-job-cleaner.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "estafette-ci-hanging-job-cleaner.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "estafette-ci-hanging-job-cleaner.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
