{{- if $.Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "estafette-ci-hanging-job-cleaner.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "estafette-ci-hanging-job-cleaner.labels" . | indent 4 }}
{{- end -}}
